// <auto-generated />
using System;
using Investify.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Investify.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240419152310_adicao enum")]
    partial class adicaoenum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Investify.Models.CargoModel", b =>
                {
                    b.Property<int>("Car_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Car_id"));

                    b.Property<string>("Car_nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Car_id");

                    b.ToTable("Cargo");
                });

            modelBuilder.Entity("Investify.Models.CarteiraModel", b =>
                {
                    b.Property<int>("Crt_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Crt_id"));

                    b.Property<DateTime>("Crt_dataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Crt_ideia")
                        .HasColumnType("int");

                    b.Property<int>("Crt_investidor")
                        .HasColumnType("int");

                    b.Property<int>("Crt_participacao")
                        .HasColumnType("int");

                    b.Property<double>("Crt_receita")
                        .HasColumnType("float");

                    b.Property<double>("Crt_valorInvestido")
                        .HasColumnType("float");

                    b.HasKey("Crt_id");

                    b.ToTable("Carteira");
                });

            modelBuilder.Entity("Investify.Models.GeneroModel", b =>
                {
                    b.Property<int>("Gen_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Gen_id"));

                    b.Property<string>("Gen_nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Gen_id");

                    b.ToTable("Genero");
                });

            modelBuilder.Entity("Investify.Models.IdeiaModel", b =>
                {
                    b.Property<int>("Ide_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ide_id"));

                    b.Property<string>("Ide_cnpj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ide_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ide_empresario")
                        .HasColumnType("int");

                    b.Property<int>("Ide_fase")
                        .HasColumnType("int");

                    b.Property<int>("Ide_nivelRisco")
                        .HasColumnType("int");

                    b.Property<string>("Ide_nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ide_participacaoDisponivel")
                        .HasColumnType("int");

                    b.Property<int>("Ide_status")
                        .HasColumnType("int");

                    b.Property<int>("Ide_tipo")
                        .HasColumnType("int");

                    b.Property<double>("Ide_valorAtual")
                        .HasColumnType("float");

                    b.Property<double>("Ide_valorInicial")
                        .HasColumnType("float");

                    b.Property<string>("ide_descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ide_id");

                    b.ToTable("Ideia");
                });

            modelBuilder.Entity("Investify.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Usu_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Usu_id"));

                    b.Property<string>("Usu_cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Usu_dataInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Usu_dataNasc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Usu_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usu_nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usu_senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usu_telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Usu_type")
                        .HasColumnType("int");

                    b.HasKey("Usu_id");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
